# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'abou'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  # - name: Featured Projects
  #   submenu:
  #     - name: MicroBam
  #       link: /projects/microbam
  #     - name: OurLegacy
  #       link: /projects/ourlegacy
  - name: Publications
    link: /
  - name: Tags
    link: /tags
  - name: A propos
    link: /about
  - name: Suivez-moi
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/abou704
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/aboubakiri-diaw-8a9a35173/
    
